modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory
license="GNU GPLv3" #mandatory

[[mods]]
modId="moguns"
version="1.7"
displayName="Mo' Guns"
authors="Code by Bomb787, art by AlanorMiga"
credits="MrCrayfish, Bomb787, AlanorMiga"
description='A simple addon for MrCrayfishs Gun Mod'

#Dependencies are an integral part of this
#We need to add forge and minecraft to run the game
#However, we also need to require the Gun mod, as well as Obfuscate
#We need the Gun Mod so we can register guns and other related stuff
#We need Obfuscate because it is a required dependency of the Gun Mod

#The fields marked with mandatory need to be present when loading the game
#They are present in the IDE as we added them to our build.gradle file
[[dependencies.moguns]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.moguns]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.moguns]]
    modId="cgm"
    mandatory=true
    versionRange="[1.2.5,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.moguns]]
    modId="framework"
    mandatory=true
    versionRange="[0.2.3,)"
    ordering="NONE"
    side="BOTH"